version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: skinbestie_postgres
    restart: unless-stopped
    env_file: .env.local
    ports:
      - "5434:5432" # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
